all: 
	g++ main.cpp GameState.cpp Board.cpp visualise.cpp pieces/pieceMove.cpp pieces/pawnMove.cpp pieces/knightMove.cpp pieces/rookMove.cpp pieces/bishopMove.cpp pieces/queenMove.cpp pieces/kingMove.cpp minimax.cpp -w -lSDL2 -lSDL2_image -fsanitize=leak -o chess
